version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mlops-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    container_name: mlops-mlflow
    restart: always
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    ports:
      - "5000:5000"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
      --default-artifact-root /mlflow-artifacts
    depends_on:
      - db

  app:
    build: .
    container_name: mlops-streamlit-app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - db
      - mlflow

volumes:
  mysql-data: